name: Lean CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install elan
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Build sample (root if lakefile exists)
        run: |
          if [ -f lakefile.lean ]; then
            lake build || true
          fi

      - name: Build Exercises subproject if present
        run: |
          if [ -d Exercises ]; then
            cd Exercises
            lake build || true
          fi

      - name: Link check placeholder
        run: |
          echo "Run link check script if available"
          if [ -f scripts/weekly-check.sh ]; then
            bash scripts/weekly-check.sh || true
          fi
